import React, { createContext, useState, useContext, useEffect } from 'react';

type Language = 'nl' | 'en' | 'de' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  nl: {
    // Nav
    'nav.home': 'Home',
    'nav.properties': 'Woningaanbod',
    'nav.about': 'Over Ons',
    'nav.contact': 'Contact',
    'nav.blog': 'Kennisbank',
    
    // Blog
    'blog.title': 'Nieuws & Inzichten',
    'blog.subtitle': 'De laatste ontwikkelingen op de woningmarkt en tips voor huurders.',
    'blog.read_more': 'Lees artikel',

    // Home
    'home.hero.title': 'Fijn wonen begint met',
    'home.hero.title.highlight': 'eerlijke kansen',
    'home.hero.subtitle': 'Geen wachtlijsten, maar een slim systeem dat iedereen een eerlijke kans geeft. Wij selecteren kandidaten op basis van objectieve criteria. Snel, vriendelijk en transparant.',
    'home.hero.cta.properties': 'Bekijk Droomwoningen',
    'home.hero.cta.how': 'Hoe werkt het?',
    'home.promise': 'Onze Belofte',
    'home.revolution': 'Huren zoals het hoort',
    'home.feat.select.title': 'Eerlijke Selectie',
    'home.feat.select.desc': 'Wij beperken de bezichtigingen tot 14 kandidaten per woning. Zo blijft het persoonlijk en maak je écht kans.',
    'home.feat.system.title': 'Slimme Match',
    'home.feat.system.desc': 'Ons platform matcht profielen direct op basis van woonwensen en stabiliteit.',
    'home.feat.quality.title': 'Kwaliteitsgarantie',
    'home.feat.quality.desc': 'Alleen gecontroleerde woningen en serieuze verhuurders. Wij staan voor kwaliteit.',
    'home.cta.title': 'Klaar voor je nieuwe thuis?',
    'home.cta.subtitle': 'Start vandaag nog jouw zoektocht.',
    'home.cta.btn': 'Bekijk woningen',

    // Properties
    'prop.title': 'Actueel Woningaanbod',
    'prop.subtitle': 'De mooiste woningen, speciaal voor jou geselecteerd.',
    'prop.new': 'Nieuw',
    'prop.per_month': '/ maand',
    'prop.btn.details': 'Bekijk & Reageer',
    'prop.not_found': 'Woning niet gevonden',
    'prop.back': 'Terug naar overzicht',

    // Property Detail
    'detail.desc': 'Omschrijving',
    'detail.specs': 'Specificaties',
    'detail.sqm': 'Oppervlakte',
    'detail.rooms': 'Kamers',
    'detail.interior': 'Interieur',
    'detail.furnished': 'Gemeubileerd',
    'detail.unfurnished': 'Kaal',
    'detail.costs_excl': 'Exclusief G/W/L en servicekosten.',
    'detail.income_req': 'Inkomensnorm',
    'detail.available': 'Beschikbaar per',
    'detail.available.now': 'Direct',
    'detail.procedure': 'Status',
    'detail.check_active': 'Inschrijving open',
    'detail.btn.start': 'Interesse? Start Inschrijving',
    'detail.btn.check_top': 'Direct kijken of u in aanmerking komt',
    'detail.disclaimer': 'Klik om vrijblijvend te kijken of je in aanmerking komt.',
    'detail.timer.hurry': 'Haast je! Sluit over:',
    'detail.deposit': 'Waarborgsom',
    'detail.deposit.1x': '1x Maandhuur',
    'detail.contract': 'Huurperiode',
    'detail.contract.12m': 'Minimaal 12 maanden',
    'detail.handover': 'Sleuteloverdracht',
    'detail.handover.time': 'Binnen 5 werkdagen',
    'detail.registration': 'Inschrijven gemeente',
    'detail.registration.yes': 'Mogelijk (verplicht)',

    // Wizard
    'wiz.title': 'Jouw Inschrijving',
    'wiz.subtitle': 'Vul je gegevens in. Ons systeem kijkt direct of er een match is.',
    'wiz.name': 'Volledige Naam',
    'wiz.email': 'E-mailadres',
    'wiz.income': 'Bruto Maandinkomen',
    'wiz.income_hint': 'Exclusief toeslagen',
    'wiz.zip': 'Huidige Postcode',
    'wiz.living': 'Leefsituatie',
    'wiz.single': 'Alleenstaand',
    'wiz.couple': 'Samenwonend',
    'wiz.family': 'Gezin',
    'wiz.student': 'Ik ben student',
    'wiz.guarantor': 'Ik heb een garantsteller',
    'wiz.add_guarantor_btn': 'Ik heb een garantsteller toevoegen',
    'wiz.pets': 'Ik heb huisdieren',
    'wiz.warning': 'Let op',
    'wiz.warning_text': 'Het opgegeven inkomen voldoet mogelijk niet aan de standaard inkomenseis (2.5x huur). U kunt doorgaan, maar dit kan uw positie beïnvloeden.',
    'wiz.btn.analyze': 'Check mijn kansen',
    'wiz.analyzing': 'Even geduld, we berekenen je positie...',
    'wiz.comparing': 'We vergelijken je profiel met de woningcriteria...',
    'wiz.congrats': 'Goed nieuws!',
    'wiz.result.text': 'Ons systeem heeft je een plek gegeven op de bezichtigingslijst. Jouw positie is:',
    'wiz.result.pos': 'Plaats',
    'wiz.result.total': 'van de 14',
    'wiz.result.explanation': 'Je behoort tot de selecte groep die mag komen bezichtigen!',
    'wiz.dates.title': 'Mogelijke Bezichtigingsmomenten',
    'wiz.dates.subtitle': 'Op basis van de huidige planning:',
    'wiz.step2': 'Verzilver je plek',
    'wiz.pay.text': 'Om deze positie (plaats 2-5) te garanderen en de uitnodiging te ontvangen, dient u de inschrijving te bevestigen middels de betaling. Hiermee bent u direct onbeperkt ingeschreven voor al ons aanbod.',
    'wiz.pay.btn': 'Bevestig & Betaal €45,00',
    'wiz.pay.secure': 'Veilig via iDeal',
    'wiz.next.title': 'Hoe nu verder?',
    'wiz.next.p1': 'Na betaling ontvangt u van ons direct een bevestiging dat u op de bezichtiging kan komen.',
    'wiz.next.p2': 'Bij de bezichtiging wordt uw positie gegarandeerd. Komt degene voor u niet opdagen? Dan schuift u een positie op naar boven.',
    'wiz.next.p3': 'Op de dag van de bezichtiging wordt vaak al bepaald of er een overeenkomst kan worden gesloten. Is de klik er? Dan is de woning van u!',
    'wiz.next.p4': 'Er wordt een dag en tijd bepaald voor het tekenen en de sleuteloverdracht; dit is vaak binnen 5 werkdagen na de bezichtiging.',
    'wiz.next.p5': 'Alle huurcontracten zijn voor minimaal 12 maanden. Bij vervroegde opzegging dient u dit formeel door te geven met een opzegtermijn van 1 maand.',

    // About
    'about.title': 'Over Dutch Rentals',
    'about.intro': 'Huren moet leuk zijn, niet stressvol. Dutch Rentals maakt de markt transparant en vriendelijk.',
    'about.mission': 'Onze Missie',
    'about.mission_text': 'Wij kiezen onze woningen met zorg uit. Geen neppe advertenties, maar echte huizen voor echte mensen.',
    'about.quality': 'Zekerheid',
    'about.quality_text': 'Elke woning is persoonlijk door ons bezocht en geverifieerd.',
    'about.process': 'Het Proces',
    'about.process_text_1': 'Ons systeem berekent eerlijk wie de beste papieren heeft, zonder aanziens des persoons.',
    'about.process_text_2': 'Vragen? Wij staan altijd voor je klaar.',
    'about.contact_btn': 'Neem contact op',

    // Terms (Headers only, content is in component)
    'terms.title': 'Algemene Voorwaarden',
    'terms.subtitle': 'Transparante afspraken voor een betrouwbare dienstverlening.',
    
    // Privacy
    'privacy.title': 'Privacyverklaring',
    'privacy.subtitle': 'Uw gegevens, veilig en conform AVG.',
  },
  en: {
    'nav.home': 'Home',
    'nav.properties': 'Properties',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'blog.title': 'News & Insights',
    'blog.subtitle': 'Latest updates on the housing market and tips for tenants.',
    'blog.read_more': 'Read article',
    'home.hero.title': 'Great living starts with',
    'home.hero.title.highlight': 'fair chances',
    'home.hero.subtitle': 'No waiting lists, but a smart system giving everyone a fair shot. We select based on objective criteria. Fast, friendly, and transparent.',
    'home.hero.cta.properties': 'View Dream Homes',
    'home.hero.cta.how': 'How it works',
    'home.promise': 'Our Promise',
    'home.revolution': 'Renting done right',
    'home.feat.select.title': 'Fair Selection',
    'home.feat.select.desc': 'We limit viewings to 14 candidates per property. This keeps it personal and gives you a real chance.',
    'home.feat.system.title': 'Smart Match',
    'home.feat.system.desc': 'Our platform matches profiles instantly based on needs and stability.',
    'home.feat.quality.title': 'Quality Assurance',
    'home.feat.quality.desc': 'Only verified homes and serious landlords. We stand for quality.',
    'home.cta.title': 'Ready for your new home?',
    'home.cta.subtitle': 'Start your search today.',
    'home.cta.btn': 'View Homes',
    'prop.title': 'Current Listings',
    'prop.subtitle': 'The finest homes, selected just for you.',
    'prop.new': 'New',
    'prop.per_month': '/ month',
    'prop.btn.details': 'View & Apply',
    'prop.not_found': 'Property not found',
    'prop.back': 'Back to overview',
    'detail.desc': 'Description',
    'detail.specs': 'Specifications',
    'detail.sqm': 'Surface',
    'detail.rooms': 'Rooms',
    'detail.interior': 'Interior',
    'detail.furnished': 'Furnished',
    'detail.unfurnished': 'Unfurnished',
    'detail.costs_excl': 'Excl. utilities and service costs.',
    'detail.income_req': 'Income standard',
    'detail.available': 'Available from',
    'detail.available.now': 'Immediately',
    'detail.procedure': 'Status',
    'detail.check_active': 'Registration open',
    'detail.btn.start': 'Interested? Start Registration',
    'detail.btn.check_top': 'Check eligibility immediately',
    'detail.disclaimer': 'Click to check eligibility without obligation.',
    'detail.timer.hurry': 'Hurry! Closing in:',
    'detail.deposit': 'Deposit',
    'detail.deposit.1x': '1x Month rent',
    'detail.contract': 'Contract duration',
    'detail.contract.12m': 'Min. 12 months',
    'detail.handover': 'Key handover',
    'detail.handover.time': 'Within 5 working days',
    'detail.registration': 'Municipal registration',
    'detail.registration.yes': 'Possible (mandatory)',
    'wiz.title': 'Your Registration',
    'wiz.subtitle': 'Enter your details. Our system instantly checks for a match.',
    'wiz.name': 'Full Name',
    'wiz.email': 'Email Address',
    'wiz.income': 'Gross Monthly Income',
    'wiz.income_hint': 'Excluding allowances',
    'wiz.zip': 'Current Zip Code',
    'wiz.living': 'Living Situation',
    'wiz.single': 'Single',
    'wiz.couple': 'Couple',
    'wiz.family': 'Family',
    'wiz.student': 'I am a student',
    'wiz.guarantor': 'I have a guarantor',
    'wiz.add_guarantor_btn': 'Add guarantor',
    'wiz.pets': 'I have pets',
    'wiz.warning': 'Note',
    'wiz.warning_text': 'The stated income may not meet the standard requirement (2.5x rent). You can proceed, but this may affect your position.',
    'wiz.btn.analyze': 'Check my chances',
    'wiz.analyzing': 'One moment, calculating your position...',
    'wiz.comparing': 'Comparing profile with property criteria...',
    'wiz.congrats': 'Good news!',
    'wiz.result.text': 'Our system has assigned you a spot on the viewing list. Your position is:',
    'wiz.result.pos': 'Place',
    'wiz.result.total': 'of 14',
    'wiz.result.explanation': 'You are part of the select group invited for a viewing!',
    'wiz.dates.title': 'Potential Viewing Dates',
    'wiz.dates.subtitle': 'Based on current schedule:',
    'wiz.step2': 'Secure your spot',
    'wiz.pay.text': 'To guarantee this position (place 2-5) and receive the invitation, you must confirm registration via payment. This gives you unlimited access to all our listings.',
    'wiz.pay.btn': 'Confirm & Pay €45.00',
    'wiz.pay.secure': 'Secure via iDeal',
    'wiz.next.title': 'What happens next?',
    'wiz.next.p1': 'After payment, you will immediately receive a confirmation that you can attend the viewing.',
    'wiz.next.p2': 'Your position is guaranteed at the viewing. If the person before you doesn\'t show up? You move up a spot.',
    'wiz.next.p3': 'On the day of the viewing, a decision is often made immediately. If there is a click, the home is yours!',
    'wiz.next.p4': 'A day and time will be set for signing and key handover; often within 5 working days after the viewing.',
    'wiz.next.p5': 'All rental contracts are for a minimum of 12 months. Early termination requires a formal notice period of 1 month.',
    'about.title': 'About Dutch Rentals',
    'about.intro': 'Renting should be fun, not stressful. Dutch Rentals makes the market transparent and friendly.',
    'about.mission': 'Our Mission',
    'about.mission_text': 'We select our homes with care. No fake ads, but real homes for real people.',
    'about.quality': 'Certainty',
    'about.quality_text': 'Every home is personally visited and verified by us.',
    'about.process': 'The Process',
    'about.process_text_1': 'Our system calculates fairly who has the best credentials, without bias.',
    'about.process_text_2': 'Questions? We are always here for you.',
    'about.contact_btn': 'Contact us',
    'terms.title': 'Terms & Conditions',
    'terms.subtitle': 'Clear agreements, reliable service.',
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'Your data is safe with us.',
  },
  de: {
    'nav.home': 'Home',
    'nav.properties': 'Wohnungen',
    'nav.about': 'Über Uns',
    'nav.contact': 'Kontakt',
    'nav.blog': 'Blog',
    'blog.title': 'Neuigkeiten & Einblicke',
    'blog.subtitle': 'Die neuesten Entwicklungen auf dem Wohnungsmarkt.',
    'blog.read_more': 'Artikel lesen',
    'home.hero.title': 'Schöner Wohnen beginnt mit',
    'home.hero.title.highlight': 'fairen Chancen',
    'home.hero.subtitle': 'Keine Wartelisten, sondern ein intelligentes System für faire Chancen. Wir wählen Kandidaten nach objektiven Kriterien. Schnell, freundlich und transparent.',
    'home.hero.cta.properties': 'Traumhäuser ansehen',
    'home.hero.cta.how': 'Wie es funktioniert',
    'home.promise': 'Unser Versprechen',
    'home.revolution': 'Mieten wie es sein soll',
    'home.feat.select.title': 'Faire Auswahl',
    'home.feat.select.desc': 'Wir beschränken Besichtigungen auf 14 Kandidaten pro Wohnung. So bleibt es persönlich und Sie haben eine echte Chance.',
    'home.feat.system.title': 'Smart Match',
    'home.feat.system.desc': 'Unsere Plattform gleicht Profile sofort basierend auf Wünschen und Stabilität ab.',
    'home.feat.quality.title': 'Qualitätsgarantie',
    'home.feat.quality.desc': 'Nur geprüfte Wohnungen und seriöse Vermieter. Wir stehen für Qualität.',
    'home.cta.title': 'Bereit für Ihr neues Zuhause?',
    'home.cta.subtitle': 'Starten Sie Ihre Suche heute.',
    'home.cta.btn': 'Wohnungen ansehen',
    'prop.title': 'Aktuelles Angebot',
    'prop.subtitle': 'Die schönsten Wohnungen, speziell für Sie ausgewählt.',
    'prop.new': 'Neu',
    'prop.per_month': '/ Monat',
    'prop.btn.details': 'Ansehen & Reagieren',
    'prop.not_found': 'Wohnung nicht gefunden',
    'prop.back': 'Zurück zur Übersicht',
    'detail.desc': 'Beschreibung',
    'detail.specs': 'Spezifikationen',
    'detail.sqm': 'Fläche',
    'detail.rooms': 'Zimmer',
    'detail.interior': 'Interieur',
    'detail.furnished': 'Möbliert',
    'detail.unfurnished': 'Unmöbliert',
    'detail.costs_excl': 'Exkl. Nebenkosten.',
    'detail.income_req': 'Einkommensnorm',
    'detail.available': 'Verfügbar ab',
    'detail.available.now': 'Sofort',
    'detail.procedure': 'Status',
    'detail.check_active': 'Anmeldung offen',
    'detail.btn.start': 'Interesse? Anmeldung starten',
    'detail.btn.check_top': 'Sofortige Prüfung auf Eignung',
    'detail.disclaimer': 'Klicken für unverbindlichen Check.',
    'detail.timer.hurry': 'Beeil dich! Endet in:',
    'detail.deposit': 'Kaution',
    'detail.deposit.1x': '1x Monatsmiete',
    'detail.contract': 'Mietdauer',
    'detail.contract.12m': 'Min. 12 Monate',
    'detail.handover': 'Schlüsselübergabe',
    'detail.handover.time': 'Innerhalb von 5 Werktagen',
    'detail.registration': 'Anmeldung Gemeinde',
    'detail.registration.yes': 'Möglich (Pflicht)',
    'wiz.title': 'Ihre Anmeldung',
    'wiz.subtitle': 'Geben Sie Ihre Daten ein. Unser System prüft sofort auf Übereinstimmung.',
    'wiz.name': 'Vollständiger Name',
    'wiz.email': 'E-Mail-Adresse',
    'wiz.income': 'Bruttomonatseinkommen',
    'wiz.income_hint': 'Ohne Zuschläge',
    'wiz.zip': 'Aktuelle PLZ',
    'wiz.living': 'Lebenssituation',
    'wiz.single': 'Alleinstehend',
    'wiz.couple': 'Paar',
    'wiz.family': 'Familie',
    'wiz.student': 'Ich bin Student',
    'wiz.guarantor': 'Ich habe einen Bürgen',
    'wiz.add_guarantor_btn': 'Bürgen hinzufügen',
    'wiz.pets': 'Ich habe Haustiere',
    'wiz.warning': 'Hinweis',
    'wiz.warning_text': 'Das angegebene Einkommen entspricht möglicherweise nicht dem Standard (2,5x Miete). Sie können fortfahren, aber dies kann Ihre Position beeinflussen.',
    'wiz.btn.analyze': 'Chancen prüfen',
    'wiz.analyzing': 'Einen Moment, wir berechnen Ihre Position...',
    'wiz.comparing': 'Wir vergleichen Ihr Profil mit den Kriterien...',
    'wiz.congrats': 'Gute Nachrichten!',
    'wiz.result.text': 'Unser System hat Ihnen einen Platz auf der Besichtigungsliste gegeben. Ihre Position ist:',
    'wiz.result.pos': 'Platz',
    'wiz.result.total': 'von 14',
    'wiz.result.explanation': 'Sie gehören zu der ausgewählten Gruppe, die besichtigen darf!',
    'wiz.dates.title': 'Mögliche Besichtigungstermine',
    'wiz.dates.subtitle': 'Basierend auf aktueller Planung:',
    'wiz.step2': 'Platz sichern',
    'wiz.pay.text': 'Um diese Position (Platz 2-5) zu garantieren und die Einladung zu erhalten, müssen Sie die Anmeldung durch Zahlung bestätigen. Damit sind Sie unbegrenzt registriert.',
    'wiz.pay.btn': 'Bestätigen & Zahlen €45,00',
    'wiz.pay.secure': 'Sicher via iDeal',
    'wiz.next.title': 'Wie geht es weiter?',
    'wiz.next.p1': 'Nach Zahlung erhalten Sie sofort eine Bestätigung für die Besichtigung.',
    'wiz.next.p2': 'Ihre Position bei der Besichtigung ist garantiert. Erscheint die Person vor Ihnen nicht? Rutschen Sie auf.',
    'wiz.next.p3': 'Am Tag der Besichtigung wird oft sofort entschieden. Stimmt die Chemie? Dann gehört die Wohnung Ihnen!',
    'wiz.next.p4': 'Ein Termin für Unterzeichnung und Schlüsselübergabe wird festgelegt; oft innerhalb von 5 Werktagen.',
    'wiz.next.p5': 'Alle Mietverträge laufen mindestens 12 Monate. Kündigung danach mit 1 Monat Frist möglich.',
    'about.title': 'Über Dutch Rentals',
    'about.intro': 'Mieten soll Spaß machen, nicht stressen. Dutch Rentals macht den Markt transparent und freundlich.',
    'about.mission': 'Unsere Mission',
    'about.mission_text': 'Wir wählen unsere Wohnungen sorgfältig aus. Keine Fake-Anzeigen, sondern echte Häuser für echte Menschen.',
    'about.quality': 'Sicherheit',
    'about.quality_text': 'Jede Wohnung wurde persönlich von uns besucht und verifiziert.',
    'about.process': 'Der Prozess',
    'about.process_text_1': 'Unser System berechnet fair, wer die besten Papiere hat, ohne Ansehen der Person.',
    'about.process_text_2': 'Fragen? Wir sind immer für Sie da.',
    'about.contact_btn': 'Kontakt aufnehmen',
    'terms.title': 'AGB',
    'terms.subtitle': 'Klare Absprachen, zuverlässiger Service.',
    'privacy.title': 'Datenschutz',
    'privacy.subtitle': 'Ihre Daten sind sicher.',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.properties': 'Propiedades',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.blog': 'Blog',
    'blog.title': 'Noticias',
    'blog.subtitle': 'Últimas actualizaciones del mercado inmobiliario.',
    'blog.read_more': 'Leer artículo',
    'home.hero.title': 'Vivir bien comienza con',
    'home.hero.title.highlight': 'oportunidades justas',
    'home.hero.subtitle': 'Sin listas de espera, sino un sistema inteligente para oportunidades justas. Seleccionamos candidatos basados en criterios objetivos. Rápido, amable y transparente.',
    'home.hero.cta.properties': 'Ver casas de ensueño',
    'home.hero.cta.how': '¿Cómo funciona?',
    'home.promise': 'Nuestra Promesa',
    'home.revolution': 'Alquilar como debe ser',
    'home.feat.select.title': 'Selección Justa',
    'home.feat.select.desc': 'Limitamos las visitas a 14 candidatos por propiedad. Así se mantiene personal y tienes una oportunidad real.',
    'home.feat.system.title': 'Match Inteligente',
    'home.feat.system.desc': 'Nuestra plataforma empareja perfiles al instante basándose en necesidades y estabilidad.',
    'home.feat.quality.title': 'Garantía de Calidad',
    'home.feat.quality.desc': 'Solo viviendas verificadas y propietarios serios. Apostamos por la calidad.',
    'home.cta.title': '¿Listo para tu nuevo hogar?',
    'home.cta.subtitle': 'Comienza tu búsqueda hoy.',
    'home.cta.btn': 'Ver viviendas',
    'prop.title': 'Oferta Actual',
    'prop.subtitle': 'Las mejores viviendas, seleccionadas especialmente para ti.',
    'prop.new': 'Nuevo',
    'prop.per_month': '/ mes',
    'prop.btn.details': 'Ver y Reaccionar',
    'prop.not_found': 'Vivienda no encontrada',
    'prop.back': 'Volver al resumen',
    'detail.desc': 'Descripción',
    'detail.specs': 'Especificaciones',
    'detail.sqm': 'Superficie',
    'detail.rooms': 'Habitaciones',
    'detail.interior': 'Interior',
    'detail.furnished': 'Amueblado',
    'detail.unfurnished': 'Sin amueblar',
    'detail.costs_excl': 'Excl. gastos de servicios.',
    'detail.income_req': 'Norma de ingresos',
    'detail.available': 'Disponible desde',
    'detail.available.now': 'Inmediatamente',
    'detail.procedure': 'Estado',
    'detail.check_active': 'Inscripción abierta',
    'detail.btn.start': '¿Interesado? Iniciar Inscripción',
    'detail.btn.check_top': 'Verificar elegibilidad inmediatamente',
    'detail.disclaimer': 'Clic para verificar elegibilidad sin compromiso.',
    'detail.timer.hurry': '¡Date prisa! Cierra en:',
    'detail.deposit': 'Fianza',
    'detail.deposit.1x': '1x Alquiler mensual',
    'detail.contract': 'Duración del contrato',
    'detail.contract.12m': 'Mín. 12 meses',
    'detail.handover': 'Entrega de llaves',
    'detail.handover.time': 'En 5 días hábiles',
    'detail.registration': 'Registro municipal',
    'detail.registration.yes': 'Posible (obligatorio)',
    'wiz.title': 'Tu Inscripción',
    'wiz.subtitle': 'Introduce tus datos. Nuestro sistema comprueba al instante si hay match.',
    'wiz.name': 'Nombre Completo',
    'wiz.email': 'Correo electrónico',
    'wiz.income': 'Ingreso Mensual Bruto',
    'wiz.income_hint': 'Excluyendo subsidios',
    'wiz.zip': 'Código Postal Actual',
    'wiz.living': 'Situación Vital',
    'wiz.single': 'Soltero',
    'wiz.couple': 'Pareja',
    'wiz.family': 'Familia',
    'wiz.student': 'Soy estudiante',
    'wiz.guarantor': 'Tengo un aval',
    'wiz.add_guarantor_btn': 'Añadir aval',
    'wiz.pets': 'Tengo mascotas',
    'wiz.warning': 'Atención',
    'wiz.warning_text': 'El ingreso indicado puede no cumplir con el requisito estándar (2.5x alquiler). Puede continuar, pero esto puede afectar su posición.',
    'wiz.btn.analyze': 'Verificar mis posibilidades',
    'wiz.analyzing': 'Un momento, calculando su posición...',
    'wiz.comparing': 'Comparando perfil con criterios de la vivienda...',
    'wiz.congrats': '¡Buenas noticias!',
    'wiz.result.text': 'Nuestro sistema te ha asignado un lugar en la lista de visitas. Tu posición es:',
    'wiz.result.pos': 'Puesto',
    'wiz.result.total': 'de 14',
    'wiz.result.explanation': '¡Perteneces al grupo selecto invitado a la visita!',
    'wiz.dates.title': 'Posibles fechas de visita',
    'wiz.dates.subtitle': 'Basado en la planificación actual:',
    'wiz.step2': 'Asegura tu lugar',
    'wiz.pay.text': 'Para garantizar esta posición (puesto 2-5) y recibir la invitación, debes confirmar la inscripción mediante pago. Esto te da acceso ilimitado.',
    'wiz.pay.btn': 'Confirmar y Pagar €45,00',
    'wiz.pay.secure': 'Seguro vía iDeal',
    'wiz.next.title': '¿Qué sigue ahora?',
    'wiz.next.p1': 'Tras el pago recibirás inmediatamente confirmación para asistir a la visita.',
    'wiz.next.p2': 'Tu posición en la visita está garantizada. ¿Si la persona delante de ti no aparece? Subes un puesto.',
    'wiz.next.p3': 'El día de la visita a menudo se decide inmediatamente. ¿Hay conexión? ¡La vivienda es tuya!',
    'wiz.next.p4': 'Se fijará día y hora para firma y entrega de llaves; a menudo dentro de 5 días hábiles.',
    'wiz.next.p5': 'Todos los contratos son por mínimo 12 meses. Terminación posterior con 1 mes de aviso.',
    'about.title': 'Sobre Dutch Rentals',
    'about.intro': 'Alquilar debe ser divertido, no estresante. Dutch Rentals hace el mercado transparente y amable.',
    'about.mission': 'Nuestra Misión',
    'about.mission_text': 'Seleccionamos nuestras viviendas con cuidado. Sin anuncios falsos, sino casas reales para gente real.',
    'about.quality': 'Seguridad',
    'about.quality_text': 'Cada vivienda ha sido visitada y verificada personalmente por nosotros.',
    'about.process': 'El Proceso',
    'about.process_text_1': 'Nuestro sistema calcula justamente quién tiene las mejores credenciales, sin prejuicios.',
    'about.process_text_2': '¿Preguntas? Siempre estamos aquí para ti.',
    'about.contact_btn': 'Contactar',
    'terms.title': 'Términos y Condiciones',
    'terms.subtitle': 'Acuerdos claros, servicio confiable.',
    'privacy.title': 'Política de Privacidad',
    'privacy.subtitle': 'Tus datos están seguros.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('nl');

  useEffect(() => {
    const browserLang = navigator.language.split('-')[0].toLowerCase();
    if (['en', 'de', 'es'].includes(browserLang)) {
      setLanguage(browserLang as Language);
    } else {
      setLanguage('nl');
    }
  }, []);

  const t = (key: string): string => {
    return translations[language][key] || translations['nl'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};